package org.carlospinan.bloqueador.app.rules

data class Country(
    val code: String,
    /**
     * The ISO 3166-1 alpha-2 regions this dialling code covers, in the order they are named.
     *
     * More than one where the code is genuinely shared: `1` is the United States and Canada, `7`
     * Russia and Kazakhstan, `212` Morocco and Western Sahara, `590` Guadeloupe and Saint Martin.
     * The picker still offers the code once — `CountryRule` has `UNIQUE(country_code)` — so the
     * display name is built by joining the regions rather than by listing the code twice.
     *
     * This is what makes the name translatable. [name] is a fixed English string compiled into the
     * app; a region code is a key the platform can turn into a name in whatever language the user
     * is reading. See [CountryNames].
     */
    val regions: List<String>,
    /**
     * English, and only a fallback. Every screen resolves the name through [CountryNames]; this is
     * what it falls back to for a region the platform does not know.
     */
    val name: String,
)

/** One region, which is all but four of them. */
private fun country(
    code: String,
    region: String,
    name: String,
) = Country(code, listOf(region), name)

/**
 * Every dialling code the country-rule picker offers, exactly once.
 *
 * The uniqueness is load-bearing, not tidiness. `CountryRule` has `UNIQUE(country_code)` and the
 * insert is `INSERT OR IGNORE`, so when two rows shared a code the second one silently did
 * nothing when the user tapped it — the country appeared in the picker and then never appeared
 * in the list. Codes covering more than one territory are named for all of them
 * ("United States / Canada") instead of being listed twice.
 *
 * [CountriesTest] pins this; adding a duplicate code fails the build's tests, not a user's.
 */

val COUNTRIES: List<Country> =
    listOf(
        country("93", "AF", "Afghanistan"),
        country("355", "AL", "Albania"),
        country("213", "DZ", "Algeria"),
        country("1684", "AS", "American Samoa"),
        country("376", "AD", "Andorra"),
        country("244", "AO", "Angola"),
        country("1264", "AI", "Anguilla"),
        country("1268", "AG", "Antigua and Barbuda"),
        country("54", "AR", "Argentina"),
        country("374", "AM", "Armenia"),
        country("297", "AW", "Aruba"),
        country("61", "AU", "Australia"),
        country("43", "AT", "Austria"),
        country("994", "AZ", "Azerbaijan"),
        country("1242", "BS", "Bahamas"),
        country("973", "BH", "Bahrain"),
        country("880", "BD", "Bangladesh"),
        country("1246", "BB", "Barbados"),
        country("375", "BY", "Belarus"),
        country("32", "BE", "Belgium"),
        country("501", "BZ", "Belize"),
        country("229", "BJ", "Benin"),
        country("1441", "BM", "Bermuda"),
        country("975", "BT", "Bhutan"),
        country("591", "BO", "Bolivia"),
        country("387", "BA", "Bosnia and Herzegovina"),
        country("267", "BW", "Botswana"),
        country("55", "BR", "Brazil"),
        country("246", "IO", "British Indian Ocean Territory"),
        country("1284", "VG", "British Virgin Islands"),
        country("673", "BN", "Brunei"),
        country("359", "BG", "Bulgaria"),
        country("226", "BF", "Burkina Faso"),
        country("257", "BI", "Burundi"),
        country("855", "KH", "Cambodia"),
        country("237", "CM", "Cameroon"),
        country("238", "CV", "Cape Verde"),
        country("1345", "KY", "Cayman Islands"),
        country("236", "CF", "Central African Republic"),
        country("235", "TD", "Chad"),
        country("56", "CL", "Chile"),
        country("86", "CN", "China"),
        country("57", "CO", "Colombia"),
        country("269", "KM", "Comoros"),
        country("242", "CG", "Congo"),
        country("243", "CD", "Congo (DRC)"),
        country("682", "CK", "Cook Islands"),
        country("506", "CR", "Costa Rica"),
        country("225", "CI", "Côte d'Ivoire"),
        country("385", "HR", "Croatia"),
        country("53", "CU", "Cuba"),
        country("357", "CY", "Cyprus"),
        country("420", "CZ", "Czech Republic"),
        country("45", "DK", "Denmark"),
        country("253", "DJ", "Djibouti"),
        country("1767", "DM", "Dominica"),
        country("1809", "DO", "Dominican Republic"),
        country("593", "EC", "Ecuador"),
        country("20", "EG", "Egypt"),
        country("503", "SV", "El Salvador"),
        country("240", "GQ", "Equatorial Guinea"),
        country("291", "ER", "Eritrea"),
        country("372", "EE", "Estonia"),
        country("251", "ET", "Ethiopia"),
        country("500", "FK", "Falkland Islands"),
        country("298", "FO", "Faroe Islands"),
        country("679", "FJ", "Fiji"),
        country("358", "FI", "Finland"),
        country("33", "FR", "France"),
        country("594", "GF", "French Guiana"),
        country("689", "PF", "French Polynesia"),
        country("241", "GA", "Gabon"),
        country("220", "GM", "Gambia"),
        country("995", "GE", "Georgia"),
        country("49", "DE", "Germany"),
        country("233", "GH", "Ghana"),
        country("350", "GI", "Gibraltar"),
        country("30", "GR", "Greece"),
        country("299", "GL", "Greenland"),
        country("1473", "GD", "Grenada"),
        Country("590", listOf("GP", "MF"), "Guadeloupe / Saint Martin"),
        country("1671", "GU", "Guam"),
        country("502", "GT", "Guatemala"),
        country("224", "GN", "Guinea"),
        country("245", "GW", "Guinea-Bissau"),
        country("592", "GY", "Guyana"),
        country("509", "HT", "Haiti"),
        country("504", "HN", "Honduras"),
        country("852", "HK", "Hong Kong"),
        country("36", "HU", "Hungary"),
        country("354", "IS", "Iceland"),
        country("91", "IN", "India"),
        country("62", "ID", "Indonesia"),
        country("98", "IR", "Iran"),
        country("964", "IQ", "Iraq"),
        country("353", "IE", "Ireland"),
        country("972", "IL", "Israel"),
        country("39", "IT", "Italy"),
        country("1876", "JM", "Jamaica"),
        country("81", "JP", "Japan"),
        country("962", "JO", "Jordan"),
        country("254", "KE", "Kenya"),
        country("686", "KI", "Kiribati"),
        country("965", "KW", "Kuwait"),
        country("996", "KG", "Kyrgyzstan"),
        country("856", "LA", "Laos"),
        country("371", "LV", "Latvia"),
        country("961", "LB", "Lebanon"),
        country("266", "LS", "Lesotho"),
        country("231", "LR", "Liberia"),
        country("218", "LY", "Libya"),
        country("423", "LI", "Liechtenstein"),
        country("370", "LT", "Lithuania"),
        country("352", "LU", "Luxembourg"),
        country("853", "MO", "Macau"),
        country("389", "MK", "North Macedonia"),
        country("261", "MG", "Madagascar"),
        country("265", "MW", "Malawi"),
        country("60", "MY", "Malaysia"),
        country("960", "MV", "Maldives"),
        country("223", "ML", "Mali"),
        country("356", "MT", "Malta"),
        country("692", "MH", "Marshall Islands"),
        country("596", "MQ", "Martinique"),
        country("222", "MR", "Mauritania"),
        country("230", "MU", "Mauritius"),
        country("52", "MX", "Mexico"),
        country("691", "FM", "Micronesia"),
        country("373", "MD", "Moldova"),
        country("377", "MC", "Monaco"),
        country("976", "MN", "Mongolia"),
        country("382", "ME", "Montenegro"),
        country("1664", "MS", "Montserrat"),
        Country("212", listOf("MA", "EH"), "Morocco / Western Sahara"),
        country("258", "MZ", "Mozambique"),
        country("95", "MM", "Myanmar"),
        country("264", "NA", "Namibia"),
        country("674", "NR", "Nauru"),
        country("977", "NP", "Nepal"),
        country("31", "NL", "Netherlands"),
        country("687", "NC", "New Caledonia"),
        country("64", "NZ", "New Zealand"),
        country("505", "NI", "Nicaragua"),
        country("227", "NE", "Niger"),
        country("234", "NG", "Nigeria"),
        country("683", "NU", "Niue"),
        country("1670", "MP", "Northern Mariana Islands"),
        country("47", "NO", "Norway"),
        country("968", "OM", "Oman"),
        country("92", "PK", "Pakistan"),
        country("680", "PW", "Palau"),
        country("970", "PS", "Palestine"),
        country("507", "PA", "Panama"),
        country("675", "PG", "Papua New Guinea"),
        country("595", "PY", "Paraguay"),
        country("51", "PE", "Peru"),
        country("63", "PH", "Philippines"),
        country("48", "PL", "Poland"),
        country("351", "PT", "Portugal"),
        country("1787", "PR", "Puerto Rico"),
        country("974", "QA", "Qatar"),
        country("262", "RE", "Réunion"),
        country("40", "RO", "Romania"),
        Country("7", listOf("RU", "KZ"), "Russia / Kazakhstan"),
        country("250", "RW", "Rwanda"),
        country("1869", "KN", "Saint Kitts and Nevis"),
        country("1758", "LC", "Saint Lucia"),
        country("508", "PM", "Saint Pierre and Miquelon"),
        country("1784", "VC", "Saint Vincent and the Grenadines"),
        country("685", "WS", "Samoa"),
        country("378", "SM", "San Marino"),
        country("239", "ST", "São Tomé and Príncipe"),
        country("966", "SA", "Saudi Arabia"),
        country("221", "SN", "Senegal"),
        country("381", "RS", "Serbia"),
        country("248", "SC", "Seychelles"),
        country("232", "SL", "Sierra Leone"),
        country("65", "SG", "Singapore"),
        country("1721", "SX", "Sint Maarten"),
        country("421", "SK", "Slovakia"),
        country("386", "SI", "Slovenia"),
        country("677", "SB", "Solomon Islands"),
        country("252", "SO", "Somalia"),
        country("27", "ZA", "South Africa"),
        country("82", "KR", "South Korea"),
        country("211", "SS", "South Sudan"),
        country("34", "ES", "Spain"),
        country("94", "LK", "Sri Lanka"),
        country("249", "SD", "Sudan"),
        country("597", "SR", "Suriname"),
        country("46", "SE", "Sweden"),
        country("41", "CH", "Switzerland"),
        country("963", "SY", "Syria"),
        country("886", "TW", "Taiwan"),
        country("992", "TJ", "Tajikistan"),
        country("255", "TZ", "Tanzania"),
        country("66", "TH", "Thailand"),
        country("670", "TL", "Timor-Leste"),
        country("228", "TG", "Togo"),
        country("690", "TK", "Tokelau"),
        country("676", "TO", "Tonga"),
        country("1868", "TT", "Trinidad and Tobago"),
        country("216", "TN", "Tunisia"),
        country("90", "TR", "Turkey"),
        country("993", "TM", "Turkmenistan"),
        country("1649", "TC", "Turks and Caicos Islands"),
        country("688", "TV", "Tuvalu"),
        country("256", "UG", "Uganda"),
        country("380", "UA", "Ukraine"),
        country("971", "AE", "United Arab Emirates"),
        country("44", "GB", "United Kingdom"),
        Country("1", listOf("US", "CA"), "United States / Canada"),
        country("598", "UY", "Uruguay"),
        country("1340", "VI", "US Virgin Islands"),
        country("998", "UZ", "Uzbekistan"),
        country("678", "VU", "Vanuatu"),
        country("379", "VA", "Vatican City"),
        country("58", "VE", "Venezuela"),
        country("84", "VN", "Vietnam"),
        country("681", "WF", "Wallis and Futuna"),
        country("967", "YE", "Yemen"),
        country("260", "ZM", "Zambia"),
        country("263", "ZW", "Zimbabwe"),
    )
